### PR TITLE
Categorisation of tasks

### PR DESCRIPTION
**Pull request by tohojo**
This is an attempt to categorise tasks into short/medium/long term, to get a
better overview, and to help others understand the current plans.

For now, this is just the tasks in the main xdp-project.org file, but I plan to
expand this to the other files as well once we are agreed that this is a good
categorisation.

I.e., don't merge this pull request yet, only for commenting!

### CODE REVIEW

**Comment by netoptimizer** [comment]
I think thing is a really good idea.

Does this collide with the agenda-view auto-detect of "Projects" and "Stuck Projects" ?

**Comment by tohojo** [comment]
> I think thing is a really good idea.

Great! I'll continue, then :)

> Does this collide with the agenda-view auto-detect of "Projects" and
> "Stuck Projects" ?

Nope, the agenda view just ignores the top-level headings, so everything
works as before.

**Comment by netoptimizer** [comment]
I find it strange that you call the "high-priority" category "short"

**Comment by tohojo** [comment]
Jesper Dangaard Brouer <notifications@github.com> writes:

> I find it strange that you call the "high-priority" category "short"

Short as in "short term". But can go with high/medium/low instead if you prefer?

**Comment by netoptimizer** [comment]
> I find it strange that you call the "high-priority" category "short"
> >  Short as in "short term". But can go with high/medium/low instead if you prefer?

I see... reading what you write elsewhere: "reflecting the urgency and time frame", and can see that your category is the "time-frame". I understand it now.

I cannot make up my mind, if "high/medium/low" would be better or worse... So, as you have "invented" this I'll leave it up to you.

**Comment by tohojo** [comment]
Jesper Dangaard Brouer <notifications@github.com> writes:

>> I find it strange that you call the "high-priority" category "short"
>> >  Short as in "short term". But can go with high/medium/low instead if you prefer?
>
> I see... reading what you write elsewhere: "reflecting the urgency and time frame", and can see that your category is the "time-frame". I understand it now.
>
> I cannot make up my mind, if "high/medium/low" would be better or worse... So, as you have "invented" this I'll leave it up to you.

Yeah, I'm not actually sure myself. Tried changing it to high/medium/low
priority, but I worry that this will make people think we imply that
their use case is low priority (which is why I went with the time-base
categorisation first). So I'm kinda inclined to change it back, actually...

**Comment by netoptimizer** [comment]
Yes... The timeframe based category could make sense, with that argument.

**Comment by tohojo** [comment]
Jesper Dangaard Brouer <notifications@github.com> writes:

> Yes... The timeframe based category could make sense, with that
> argument.

Cool, will revert to that, and see if I can come up with better
mnemonics for the tag names...

**Comment by tohojo** [comment]
Failed to come up with better tag names, so just going to merge this as-is...

**Pull request merged**
