### PR TITLE
Netdevconf2020 slide updates(2)

### PR DESCRIPTION
**Pull request by netoptimizer**
Hi @LorenzoBianconi 

I've done some of the things you mentioned in #40 
https://github.com/xdp-project/xdp-project/pull/40#pullrequestreview-457316978

### CODE REVIEW

**Comment by netoptimizer** [comment]
Ups, I see  that #41 already have some of this work

**Comment by LorenzoBianconi** [comment]
@netoptimizer no worries, I will review your changes and I will apply the diff ontop of them (I have a long trip tomorrow :)). What about the slide #2? I think it is already covered later. What about adding some XDP use cases instead?

**Comment by netoptimizer** [comment]
> What about the slide 2? I think it is already covered later.

The purpose of slide 2 is to say (and show only 14 lines) that the core XDP RX-handler is fairly simple.
And then it says: "Tricky part is changing driver memory model to be compatible with XDP"
which explains why we are talking about `page_pool` API later.

> What about adding some XDP use cases instead?

Not use-cases IMHO. We don't have time for use-cases (plenty of other talks explain what XDP is and what it can be used for)

We do need an intro slide, that explains that the target audience is.
IMHO the target audience is driver developers that need to extend their existing driver to support XDP.

**Comment by LorenzoBianconi** [comment]
> be
> > What about the slide 2? I think it is already covered later.
> 
> The purpose of slide 2 is to say (and show only 14 lines) that the core XDP RX-handler is fairly simple.
> And then it says: "Tricky part is changing driver memory model to be compatible with XDP"
> which explains why we are talking about `page_pool` API later.
> 

ack

> > What about adding some XDP use cases instead?
> 
> Not use-cases IMHO. We don't have time for use-cases (plenty of other talks explain what XDP is and what it can be used for)
> 

ack

> We do need an intro slide, that explains that the target audience is.
> IMHO the target audience is driver developers that need to extend their existing driver to support XDP.

ack, I can work on it tomorrow. What about the diff between the PR #41 and your PR?

**Comment by netoptimizer** [comment]
> What about the diff between the PR #41 and your PR?

Don't worry about my changes in this #42, we can just close this.

**Comment by LorenzoBianconi** [comment]
> > What about the diff between the PR #41 and your PR?
> 
> Don't worry about my changes in this #42, we can just close this.

ack, so I will close #42 , and I will apply #41

**Pull request closed without merging**
